version: '3'

services:
  node:
    build: .
    networks:
      - proxy
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3010:3010
    env_file:
      - .env
    command: npm start

networks:
  proxy:
    external: true